apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "redpanda.default.svc.cluster.local:9092"
  - name: consumerGroup
    value: "todo-app"
  - name: authType
    value: "none"
